# Generated by Django 2.0 on 2019-05-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='image_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image'),
        ),
    ]
