# Generated by Django 2.0 on 2019-05-10 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190510_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(to='gallery.tags'),
        ),
    ]
