# Generated by Django 2.0 on 2019-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190510_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
