# Generated by Django 2.0 on 2019-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_category',
            field=models.CharField(choices=[('Music', 'Music'), ('Travel', 'Travel'), ('Food', 'Food')], default='', max_length=30),
        ),
    ]
