# Generated by Django 2.0 on 2019-05-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190512_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.Image'),
        ),
    ]
